### ISSUE TITLE
[Enhancement] Transparent background for Popup

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/XamarinCommunityToolkit#1097]
### Summary
Hi! i know it's still in preview but i have a popup in my pet project that has UWP(sadly it's not implemented yet) and iOS and Android versions and i really wanted to replace the ...... popup with XCT's (because i love how XCT puts native popup into the projects) and i have a issue with **setting background of popup to transparent**.

also i just found out in iOS we have a padding and radius that we can't change 🤦‍♂️ and the material frame acrylic not working on it as it should be.

### Screenshot

![image](https://user-images.githubusercontent.com/42671084/111742495-89ea2a80-889d-11eb-9e40-12f64c2f49b5.png)
![IMG_0951](https://user-images.githubusercontent.com/42671084/111745736-45ad5900-88a2-11eb-879f-7a0e267d2aba.PNG)

**Comment by AndreiMisiukevich** [comment]
Hey @ahoefling any chance to take a look at this?

**Comment by ahoefling** [comment]
I'm more than happy to look at this. Can you share a sample project or the popup XAML/c#.

**Comment by mhrastegary77** [comment]
Yeah sure!
[issue1097.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6174977/issue1097.zip)

**Comment by ahoefling** [comment]
@mhrastegary77 I downloaded your sample code and made some changes to it to help get you a little further with XCT Popups. 

You need to add the following property to your XAML `Color="Transparent"`. This will set the color of popup independent of the content control. In your example you use the `sh:MaterialFrame` with rounded corners, which is your main control. The native popup will need to have the Transparent Color so the user only sees the `sh:MaterialFrame`.

Here is an updated XAML snippet
```xml
<?xml version="1.0" encoding="utf-8" ?>
<xct:Popup
    x:Class="issue1097.PopupView"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:sh="http://sharpnado.com"
    xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
    Size="300,365"
    Color="Transparent"> <!-- this was the change to get it working -->

  <!-- omitted xaml -->

</xct:Popup>
```

# Feature Parity Table
Most of the features work across the 3 major platforms (iOS, Android, and UWP), but not all of them have been implemented. The original Pull Request documents what works and what doesn't (#653). Below is a screenshot of our current feature parity table

![image](https://user-images.githubusercontent.com/17751436/111876215-19620d00-8974-11eb-97ba-fa6157de3804.png)


# Screenshots
## Screenshot - Android
![image](https://user-images.githubusercontent.com/17751436/111876140-c12b0b00-8973-11eb-9408-0d3d4fd9b642.png)


## Screenshot - UWP
UWP requires the min target version to be 19041 - this may change before 1.1.0 is released but right now if you don't set this correctly the Popup will throw a runtime exception.
![image](https://user-images.githubusercontent.com/17751436/111876269-5fb76c00-8974-11eb-9b02-6b836c484923.png)

Since UWP has a default border on the Flyout, if you want it to be transparent you will need to set the border color to transparent. There is an attached property `BorderColor` that is available in the windows specific `xmlns`

**Add xmlns to Popup Element**
```
xmlns:xctwin="clr-namespace:Xamarin.CommunityToolkit.UI.Views.WindowsSpecific;assembly=Xamarin.CommunityToolkit"
```

**Add Attached Property BorderColor**
```
xctwin:Popup.BorderColor="Transparent"
```

**Full XAML**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<xct:Popup
    x:Class="issue1097.PopupView"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:sh="http://sharpnado.com"
    xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
    xmlns:xctwin="clr-namespace:Xamarin.CommunityToolkit.UI.Views.WindowsSpecific;assembly=Xamarin.CommunityToolkit"
    Size="300,365"
    Color="Transparent"
    xctwin:Popup.BorderColor="Transparent"> <!-- add windows specific namespace and attached property for border color -->
  <!-- omitted xaml --.

</xct:Popup>
```

![image](https://user-images.githubusercontent.com/17751436/111876718-6b0b9700-8976-11eb-8d62-92a7d0a85ea1.png)

## Screenshot - iOS (Not Implemented)
While iOS is implemented using native popups, that transparency feature is not currently implemented. PRs are always welcomed

# Sample Code
I have updated your sample code with the changes above to help you get going faster.

[issue1097_Update1.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6175965/issue1097_Update1.zip)

**Comment by mhrastegary77** [comment]
WOW! this is amazing Andrew, i don't know what to say! thanks!!!❤
btw i tried with BackgroundColor and Background and didn't work. i didn't know about that Color property, sorry :(

**Comment by pictos** [comment]
@mhrastegary77 if the property name was `BackgroundColor` or `PopUpBackgroundColor` do you think that you could found it easier?

**Comment by mhrastegary77** [comment]
well, i didn't.

**Comment by pictos** [comment]
The current name is `Color` and not `BackgroundColor`, I'm asking because if you feel that another name would be more intuitive we can see if we can change the name

**Comment by ahoefling** [comment]
@pictos I think our biggest problem is we don't have the documentation put together for this. People have to guess on the API or read the implementation details. The XML docs don't really work in the XAML editor. It should be a slightly better dev experience for C# views.

This is mainly my fault as I haven't had the time to write the docs yet 😞

**Comment by pictos** [comment]
IF you feel that the prop. the name will not make it easier to discover let's keep at it's. @mhrastegary77  Can we close this issue?

**Comment by mhrastegary77** [comment]
No @ahoefling  it's not your fault ❤

ok i will @pictos 👀

**Comment by pictos** [comment]
Thanks @mhrastegary77

**Comment by JunkyXL86** [comment]
> 
> 
> The current name is `Color` and not `BackgroundColor`, I'm asking because if you feel that another name would be more intuitive we can see if we can change the name

Yes for sure. Background(Color) is the only intuitive name for setting a background like in the entire world of Xamarin.Forms.
I had the exact same problem setting a transparent background color and it made me look for alternative popup solutions until I stumbled upon this 'Color' hint in here 🤦‍♂

Why is there an own property for setting the background color?
