### ISSUE TITLE
[Discussion] How to get started?

### ISSUE THREAD

**Issue by sthewissen** [xamarin/XamarinCommunityToolkit#115]
There's currently quite a bit of code in a few of the existing branches. However, I think the cleanest way to approach this is to create a clean `reboot` type branch and rebuild from the ground up. Picking bits and bobs from the other branches that we still think are relevant to the project (and removing these branches afterwards). I guess the current `not-active` branch can be a starting point for that.

![image](https://user-images.githubusercontent.com/2419439/83245541-27eef600-a1a1-11ea-9469-ab7ca7d6e645.png)

How do you all feel about this?

**Comment by AndreiMisiukevich** [comment]
@sthewissen my "young blood" hints me that I want to make a new community kit from scratch :)

1) I think we can create a new **legacy** branch from the head of the **master** (it will have "old" master code.
2) Totally clean history of **master** branch. 

Is is so radical?

**Comment by sthewissen** [comment]
I don't think that's so radical. The only thing I'm not sure of is the state of the other branches that currently exist and whether or not they are all even necessary to keep around at this point. People involved in the previous reboot of this project might know better than I do. cc: @Depechie @bartlannoeye

**Comment by jfversluis** [comment]
# Code
I think that makes sense. Leave the not-active branch as the default for now while we get some things in place to show to the world.

We might want to go through the (now legacy) code that is still there and see what we want to take from that. Of course, combined with the general idea where we want to go with this thing.

I think for a lot of things we can draw inspiration from Essentials since it's a similar concept with a different angle.

Code-wise I would say start from scratch. Start from 0 with multi-targeting and other awesome stuff that is now available. Just copy in the bits that we want to take from the vLegacy.

# Contributors/community
The other thing I would focus on is community engagement. I mean, it's a _community_ toolkit. 

We need to make an effort to make it as easy as possible to get onboarded and add things. Good documentation on that, maybe some videos/streams and set expectations on what we would like to see and how we would want to see them. And in return; what can they expect from us.

I think we can really benefit from combining a couple of great (features of) libraries into something like this to make them more discoverable and sustainable. I liked David's comment on this being a more low barrier project to contribute to before Forms. Let this be a project where first-timers can get the hang of it and hopefully it will rub off on other projects as well.

If we give this some thought while building this from the ground up, we can incorporate all the good habits into our workflow and everyone will benefit from that.

**Comment by jfversluis** [comment]
I think most of this is done and issues coming off this are already created or can be created to track progress on that separately
