### ISSUE TITLE
[Enhancement] add more states for LayoutState

### ISSUE THREAD

**Issue by alex-relov** [xamarin/XamarinCommunityToolkit#1165]
## Summary

add more states for Xamarin.CommunityToolkit.UI.Views.ayoutState:  NoInternet, Unauthorized

## Who Will Do The Work?

- [x] I am willing to take this on myself

**Comment by Cfun1** [comment]
Hi thanks for the contribution, but IMHO this two states doesn't need to be added as it can be used with Custom states like in [the sample app, ](https://github.com/xamarin/XamarinCommunityToolkit/blob/8f2975254ddca1ff920e6e805afc421c67975c64/samples/XCT.Sample/ViewModels/Views/StateLayoutViewModel.cs#L57-L61) and here's the [xaml part](https://github.com/xamarin/XamarinCommunityToolkit/blob/8f2975254ddca1ff920e6e805afc421c67975c64/samples/XCT.Sample/Pages/Views/StateLayoutPage.xaml#L73-L80) especially that is easy to create a custom one. I am thinking that because it's likely others will want to add some special States too, like "NoSignal", "AirPlaneMode", "NoBlutooth", "Authentified"...

**Comment by alex-relov** [comment]
@Cfun1 perhaps, but I believe that these two states are typical and exist in almost every application

**Comment by AndreiMisiukevich** [comment]
@jfversluis @pictos and especially @sthewissen what do you think about this enhancement?

**Comment by pictos** [comment]
I'm with @Cfun1 on this one, it's very easy to add a new custom state

**Comment by jfversluis** [comment]
Yep, custom states are to be added yourself else we can go to infinity with this.

However, @alex-relov we really appreciate your input so thank you for that, but we're not going to move forward on this one. Looking forward to your next proposal!
