### ISSUE TITLE
[Enhancement] HeaderTemplate in Expander control

### ISSUE THREAD

**Issue by bbenetskyy** [xamarin/XamarinCommunityToolkit#1256]
## Summary

Hi, I really miss `HeaderTemplate` in `Expander` control.

`Expander` itself already contains `ContentTemplate` and it would be really nice to have not only `Expander.Header` but to have `Expander.HeaderTemplate` as well.

Thanks 😊

## API Changes

Same as we have `Content` and `ContentTemplate` we need `Header` and `HeaderTemplate` and we can use one of them:

```xaml
<xct:Expander>
    <xct:Expander.Header>
        <!-- Grid or StackLayout or anything else like root of Header -->
    </xct:Expander.Header>
</xct:Expander>
```

and

```xaml
<DataTemplate x:Key="CoolHeaderTemplate" x:DataType="models:SomeCoolModel">
    <!-- Grid or StackLayout or anything else like root of Header -->
</DataTemplate>

<xct:Expander HeaderTemplate="{StaticResource CoolHeaderTemplate}" />

<xct:Expander>
    <xct:Expander.HeaderTemplate>
        <DataTemplate x:Key="CoolHeaderTemplate" x:DataType="models:SomeCoolModel">
            <!-- Grid or StackLayout or anything else like root of Header -->
        </DataTemplate>
    </xct:Expander.HeaderTemplate>
</xct:Expander>
```

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by AndreiMisiukevich** [comment]
Hi @bbenetskyy and thank you for your interest in this project :)

Could you please show a use-case where it can be applied? I mean where it can be useful.

ContentTemplate exists due to lazy loading purpose. If expander is collapsed (by default) then we can "save" time for creating and rendering its content. Instead, we will render content "on the fly" once it is requested. That's why we use DataTemplate.

But since Header is always shown, I don't see any reason for adding data template. Because anyway a view will be created once we set the template.


Thanks

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
