### ISSUE TITLE
[Bug] Error: Failed to create captire sesstion

### ISSUE THREAD

**Issue by andrecostanunes** [xamarin/XamarinCommunityToolkit#1259]
I get the error: "Failed to create capture session" when trying to use the front camera on the Xiaomi Redmi note 7 Android 10 device.

**Comment by danardelean** [comment]
Have you tried the sample application and you encounter the same error?

**Comment by brminnick** [comment]
Hi @andrecostanunes! Please upload/link a reproduction sample to help us verify + fix this bug.

**Comment by jfversluis** [comment]
Friendly ping to provide us with some more info. If not, I'm inclined to close one soon.

**Comment by kainaalmeida** [comment]
Hi! 

https://user-images.githubusercontent.com/7945253/121115317-51e2eb80-c7eb-11eb-879a-453d737ca5bd.mp4

When I try to use the front camera on Redmi Note 8 - Android 10, nothing happens. I am using the example application.

**Comment by Axemasta** [comment]
We are experiencing this crash on Redmi Note 7 - Android 10, no other device.

Looking at the android docs ([here](https://developer.android.com/reference/android/hardware/camera2/CameraCaptureSession.StateCallback#onConfigureFailed(android.hardware.camera2.CameraCaptureSession))):
> This method is called if the session cannot be configured as requested.
>
> This can happen if the set of requested outputs contains unsupported sizes, or too many outputs are requested at once.

I'll have a play with the surfaces being passed in, since its possible that one of the paths used to setup the surfaces is causing an issue.

If I find anything that identifies or fixes the problem I will raise a PR. It seems like you can't replicate this issue without the specific device in question 😅

**Comment by Axemasta** [comment]
Hi guys, I've raised a PR to address this issue. Please if you get the chance could you run my branch & verify the camera is functioning on your Xiaomi devices 😇

@andrecostanunes @kainaalmeida
