### ISSUE TITLE
[Bug] TouchEffect does not revert Button State from Pressed to Normal

### ISSUE THREAD

**Issue by RenegadeVile** [xamarin/XamarinCommunityToolkit#1342]
### Description

I am using TouchEffect from the Xamarin Community Toolkit to add Pressed animations to my buttons. However, I noticed there was no option to animate TextColor so I used the VisualStateManager to switch the TextColor when Pressed instead. However, it appears that using TouchEffect and Visual States together causes some issues. After clicking the button, the TextColor changes in accordance to its Pressed visual state, but after releasing the button, the TextColor does not revert back to what it should be according to the Button's Normal visual state. When removing all TouchEffect properties from the Button's style, the TextColor **does** revert as expected. I've experimented with other properties beyond TextColor, such as Opacity or BorderWidth with identical results.

### Steps to Reproduce

1. Create any Xamarin.Forms project.
2. Add a Button to the MainPage.xaml and set its xct:TouchEffect.BackgroundColor animation properties for Normal and Pressed to any color.
3. Add Visual States to the Button for Normal and Pressed that set its TextColor to two different colors in each state.
4. Run the app and click the button. Upon pressing its background color will change according to the TouchEffect animation and its TextColor will change according to the Pressed state. Releasing will revert the background color as expected, but not the TextColor, which will stay in its Pressed state.

### Expected Behavior

The Button should go from its Pressed state to the Normal state after the tap.

### Actual Behavior

The Button appears to remain in its Pressed state indefinitely.

### Basic Information

- Version with issue: 1.2.0-pre2
- IDE: Visual Studio 2019 Community Edition
- Platform Target Frameworks:
  - Android: 10

### Workaround

Manually setting the state of the button after the press might be a workaround but I have not looked into this.

### Reproduction imagery

![Screenshots](https://user-images.githubusercontent.com/80963583/120104991-62de8d80-c157-11eb-989b-5881cee0bc34.png)

**Comment by AndreiMisiukevich** [comment]
Hi @RenegadeVile thanks for your report
You should use the "Unpressed" state name.

https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/TouchEffect.shared.cs#L11-L15

I had to change it from "Normal" to "Unpressed" due to naming conflict with (Normal name is already reserved)
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager

Sorry, there is no documentation for TouchEffect yet... but once it appears, this info will be specified there.

Best Regard!
