### ISSUE TITLE
[Bug] [Android] ToolkitPlatform.Context used by AvatarView is causing a NullReferenceException

### ISSUE THREAD

**Issue by Cfun1** [xamarin/XamarinCommunityToolkit#1345]
### Description
`AvatarView` causing a `System.NullReferenceException` at this line https://github.com/xamarin/XamarinCommunityToolkit/blob/7db4941a02e16dfd8151c3df198954dbc17a0be1/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/AvatarView/ImageSourceValidator.android.ios.macos.uwp.wpf.gtk.tizen.cs#L43 because of `ToolkitPlatform.Context` https://github.com/xamarin/XamarinCommunityToolkit/blob/aba6205274a7fb8c8a55eaedb8001e3a693ed5f1/src/CommunityToolkit/Xamarin.CommunityToolkit/Startup/ToolkitPlatform.android.cs#L21
### Steps to Reproduce

1. Run the app, click on physical back button.

### Expected Behavior
No exception should be thrown.
### Actual Behavior
Exception thrown: System.NullReferenceException: 'Object reference not set to an instance of an object.'

### Basic Information
- Version with issue: 1.2.0-pre2
- Last known good version: -
- Platform Target Frameworks: Tested on Android only.
  - iOS:  
  - Android 10:  
  - UWP:   
- Affected Devices: Emulator and real devices.

 ### Reproduction Link
https://github.com/Cfun1/XamsungHealth

cc @pictos

**Comment by AndreiMisiukevich** [comment]
Hmmm, should we do lazy loading of context (store context after first request)

**Comment by pictos** [comment]
@AndreiMisiukevich Yes, I believe that will be the best approach, I already did a fix for it, but need to find it again on my branches ocean. 

More info for others that want to know more about it:

In this case, the issue is because when you press the back button, the app goes to background and when the avatarView tries to access the `Context` that's `null` because there's no `MainPage`, but the context keeps the same (because the way how Forms works)
