### ISSUE TITLE
[Bug] TextCaseConverter

### ISSUE THREAD

**Issue by angelru** [xamarin/XamarinCommunityToolkit#1354]
I am using the converter on a custom control to a `Text` property that has `BindingMode.TwoWay`

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: The method or operation is not implemented.
[mono-rt]   at Xamarin.CommunityToolkit.Converters.TextCaseConverter.ConvertBack (System.Object value, System.Type targetType, System.Object parameter, System.Globalization.CultureInfo culture) [0x00000] in <5265966be8d2407fb7a4c3b38c6441d7>:0 
```

**Comment by jfversluis** [comment]
That is correct, this would call the `ConvertBack` method which [is not implemented](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Converters/TextCaseConverter.shared.cs#L50) because there is no way of knowing how to convert back. If you change the casing, the original information is lost.
