### ISSUE TITLE
[Bug] TouchEffect should not propagate event to parent layout

### ISSUE THREAD

**Issue by unamed000** [xamarin/XamarinCommunityToolkit#1432]
## Summary

TouchEffect bindable effect should not allow event propagate to parent when child view is already consumed the event, just like TapGestureRecognizer

## Intended Use Case
If i have a layout like this:

ContentView TouchEffect.Command=Click1Command

ContentView2 (inside ContentView) TouchEffect.Command=Click2Command

When i tap on ContentView2, the Click2Command is triggered, but not Click1Command
For now the event from ContentView 1 will also be triggered

## Who Will Do The Work?

- [ ] I am willing to take this on myself
- [x] Just putting this out there for someone to pick up

**Comment by Andreas0xffff** [comment]
Can it be that the problem only exists under iOS?

**Comment by Andreas0xffff** [comment]
## Bug on iOS 
![Animation](https://user-images.githubusercontent.com/23099353/123394741-c1a0f680-d59f-11eb-9905-3789de330b70.gif)

## Android is fine
![Animation2](https://user-images.githubusercontent.com/23099353/123395206-3bd17b00-d5a0-11eb-833b-06f94fad6195.gif)

## Complained behaviour
When the red layout gets tapped (xct:TouchEffect), the blue command is also tapped.

## Expected behaviour
The blue command should not be executed when the red layout gets tapped.
The left side should react like the right side of the page:
When the green layout gets tapped (TapGestureRecognizer), the underlying purple tap event is not triggered

## It is reproducible with the following XAML.

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
			 x:Class="MainPage"
			 x:Name="page">

	<Grid
		ColumnDefinitions="*,*">
		
		<AbsoluteLayout
			Grid.Column="0"
			BackgroundColor="Blue"
			xct:TouchEffect.NativeAnimation="true"
			xct:TouchEffect.Command="{Binding Blue_Tapped, Source={x:Reference page}}">
			
			<StackLayout
				AbsoluteLayout.LayoutFlags="All"
				AbsoluteLayout.LayoutBounds="0.5,0.5,0.8,0.8"
				BackgroundColor="Red"
				xct:TouchEffect.NativeAnimation="true"
				xct:TouchEffect.Command="{Binding Red_Tapped, Source={x:Reference page}}">

			</StackLayout>

		</AbsoluteLayout>

		<AbsoluteLayout
			Grid.Column="1"
			BackgroundColor="Purple">

			<AbsoluteLayout.GestureRecognizers>
				<TapGestureRecognizer Tapped="TapGestureRecognizerPurple_Tapped"/>
			</AbsoluteLayout.GestureRecognizers>

			<StackLayout
				AbsoluteLayout.LayoutFlags="All"
				AbsoluteLayout.LayoutBounds="0.5,0.5,0.8,0.8"
				BackgroundColor="Green">
				
				<StackLayout.GestureRecognizers>
					<TapGestureRecognizer Tapped="TapGestureRecognizerGreen_Tapped"/>
				</StackLayout.GestureRecognizers>

			</StackLayout>

		</AbsoluteLayout>
		
	</Grid>

</ContentPage>

**Comment by unamed000** [comment]
Hi @andreas-nesheim 

You're right, i don't have the same problem in Android

**Comment by Andreas0xffff** [comment]
Maybe the `ShouldReceiveTouch()` function should be implemented in `TouchEffect`, like it is in the TapGestureRecognizer:

[Xamarin.Forms EventTracker ShouldReceiveTouch](https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.iOS/EventTracker.cs#L655)

**Comment by Tommigun1980** [comment]
I also have a very very hard time using the touch effect because it works differently on iOS and Android.

**Comment by Tommigun1980** [comment]
This is probably related to my issue https://github.com/xamarin/XamarinCommunityToolkit/issues/842.

**Comment by AndreiMisiukevich** [comment]
Hey @unamed000 please verify that my PR https://github.com/xamarin/XamarinCommunityToolkit/pull/1435 fixes your issue please
