### ISSUE TITLE
[Bug][iOS only] TouchEffect NativeAnimation doesn't reset animated properties when used on ScrollView

### ISSUE THREAD

**Issue by Andreas0xffff** [xamarin/XamarinCommunityToolkit#1433]
### Description
When using TouchEffect NativeAnimation with a view that's positionend on a ScrollView or SwipeView, the animation doesn't reset the animated properties reliable.
As soon as a scroll of the ScrollView occurs during the tapevent, the animation is interrupted in the middle and not reset.

![Animation](https://user-images.githubusercontent.com/23099353/123380402-b0e88480-d58f-11eb-9be5-72c2654d1389.gif)

### Steps to Reproduce

1. Start the XCT.Sample project and go to the TouchEffectPage.
2. Scroll down to the button that's labeled 'Image | Native'.
3. Tap the button, hold the tap and pan/scroll.

### Expected Behavior
The changed properties of the UIView.AnimateAsync()-Animation should be reseted.

### Actual Behavior
The FadeOutEffect (Opacity-Change) remains.
When using the NativeAnimationColor, the Color-Change remains.

### Basic Information

- Version with issue: Newest
- Last known good version: None
- IDE: Visual Studio 2019 16.10.2 Windows

- Platform Target Frameworks: 
  - iOS:  14.5

**Comment by Huaba93** [comment]
We have the same problem. The issue is caused by this line
https://github.com/xamarin/XamarinCommunityToolkit/blob/365b0cf316afded845ca094b1abe1d8357d9ab64/src/CommunityToolkit/Xamarin.CommunityToolkit/Effects/Touch/PlatformTouchEffect.ios.cs#L275

When removing it, I cannot reproduce the issue anymore. 

@AndreiMisiukevich any idea how to fix this?

**Comment by AndreiMisiukevich** [comment]
@Huaba93 thanks for the investigation) The fix is on its way ;)
