### ISSUE TITLE
[Enhancement] ChatList / MessagesList

### ISSUE THREAD

**Issue by coen22** [xamarin/XamarinCommunityToolkit#1455]
## Summary
In Xamarin Forms it's currently quite difficult to make a smooth Chat UI without a custom renderer (at least this has been my experience). And even then it had performance issues on Android.

## API Changes

Could you maybe create an API that wraps around some native Chat UI components on both iOS and Android?
https://github.com/stfalcon-studio/ChatKit (Android)
https://github.com/MessageKit/MessageKit (iOS)

e.g. you could have something like this.

    var chat = new MessagesList {
        ShowDateHeader = true,
        Bubbles { // or children
            new CustomMessageBubble {
                SendAt = DateTime.UtcNow,
                Content = new Button {
                    Text = "Hey"
                }
            },
            new TextMessageBubble {
                SendAt = DateTime.UtcNow,
                Text = "Hey"
            }
        }
    }

    Content = chat;

## Intended Use Case
I think many applications can benefit from a user-friendly Chat UI.

## Who Will Do The Work?
- [ ] I am willing to take this on myself
- [ ] Just putting this out there for someone to pick up
- [x] I'd love to be involved in adding this to XCT, but I'm not an expert

**Comment by jfversluis** [comment]
Hey Coen!

I love the last option you added there! And seeing your name seemed Dutch, I looked at your profile and you're in Maastricht?! You're like my neighbor! 🙀

Anyway, the important stuff. We'd love to have something like this. A lot of people seem to want it. However, seeing the current velocity and future of this package I feel that this might be too much to take on right now. What I mean by "future of this package" will become official pretty soon, but as you might expect, the lifetime in its current form is limited. This is tied to Xamarin.Forms and Xamarin.Forms will soon transition into .NET MAUI.

I think if we were to make something like this it would be in the .NET MAUI timeframe and not so much in the lifespan of this Toolkit. Does that make sense?

In the meantime I think Telerik and SyncFusion both have great components for this if you really need it right now.

If you really want to get involved make sure to reach out since you live so close it will be fun to have a chat and we can see if I can get you up to speed.

Thanks for the suggestion!

**Comment by coen22** [comment]
> Hey Coen!
> 
> I love the last option you added there! And seeing your name seemed Dutch, I looked at your profile and you're in Maastricht?! You're like my neighbor! 🙀

Haha, yes I live in Maastricht, we should go for coffee sometime!

> Anyway, the important stuff. We'd love to have something like this. A lot of people seem to want it. However, seeing the current velocity and future of this package I feel that this might be too much to take on right now. What I mean by "future of this package" will become official pretty soon, but as you might expect, the lifetime in its current form is limited. This is tied to Xamarin.Forms and Xamarin.Forms will soon transition into .NET MAUI.
> 
> I think if we were to make something like this it would be in the .NET MAUI timeframe and not so much in the lifespan of this Toolkit. Does that make sense?

Yes, that makes sense, I also posted this request on the MAUI repo, but they told me to post it here :D but it would nice to have this in a Maui Community Toolkit.

> In the meantime I think Telerik and SyncFusion both have great components for this if you really need it right now.

I'm using a collectionview right now, but if you scroll too quickly, it's not great. I'm using it to make a free app for finding a dance partner (as that's been a bit difficult during corona). So I'm not really looking for a paid plugin.

> If you really want to get involved make sure to reach out since you live so close it will be fun to have a chat and we can see if I can get you up to speed.

Yeah, I'd like that.

> Thanks for the suggestion!

**Comment by jfversluis** [comment]
SyncFusion has the [community license](https://www.syncfusion.com/products/communitylicense) which is free and it seems like you qualify :)

Find my email on my GitHub profile and shoot me a message, we'll see about that coffee!
