### ISSUE TITLE
NullReferenceException thrown in PopupRenderer.SetViewController when using in embedded forms scenario

### ISSUE THREAD

**Issue by follesoe** [xamarin/XamarinCommunityToolkit#1758]
### Description

I am trying to use the Popup View in a Xamarin.iOS application embedding some Xamarin.Forms views, a technique described in the Xamarin.Forms documentation here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms

When calling `Xamarin.Forms.Application.Current.MainPage.Navigation.ShowPopup(popup);` I get a null reference exception, as shown in the stack trace.

### Stack Trace

```shell
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.CommunityToolkit.UI.Views.PopupRenderer.SetViewController () [0x00089] in <be1d33109c044cbba821f6c39d395abb>:0 
  at Xamarin.CommunityToolkit.UI.Views.PopupRenderer.OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x0001f] in <be1d33109c044cbba821f6c39d395abb>:0 
  at Xamarin.CommunityToolkit.UI.Views.PopupRenderer.Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x0008d] in <be1d33109c044cbba821f6c39d395abb>:0 
  at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00032] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:240 
  at Xamarin.CommunityToolkit.Extensions.NavigationExtensions.PlatformShowPopup (Xamarin.CommunityToolkit.UI.Views.BasePopup popup) [0x00000] in <be1d33109c044cbba821f6c39d395abb>:0 
  at Xamarin.CommunityToolkit.Extensions.NavigationExtensions.ShowPopup (Xamarin.Forms.INavigation navigation, Xamarin.CommunityToolkit.UI.Views.BasePopup popup) [0x00000] in <be1d33109c044cbba821f6c39d395abb>:0 
  at XctEmbedDemo.MainViewController.OnTouchUpInside (System.Object sender, System.EventArgs e) [0x0000d] in /Users/follesoe/Projects/XctEmbedDemo/XctEmbedDemo/MainViewController.cs:51
```

### Link to Reproduction Sample

I have created a minimal Xamarin.iOS application referencing the latest builds of Xamarin.Forms and Xamarin.CommunityToolkit that will trigger this issue: https://github.com/follesoe/XctEmbedDemo

### Steps to Reproduce

1. Run the example application
2. Tap the button
3. Observe the null reference exception

### Expected Behavior

I would expect the popup to appear, or at least get a meaningful error saying I am using the component in an unsupported way.

### Actual Behavior

Null reference exception is thrown.

### Basic Information

- Version with issue: 1.3.1
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  15.0, 
  - Xamarin.iOS: 15.2.0.17 
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pictos** [comment]
@follesoe probably the NRE is from here
https://github.com/xamarin/XamarinCommunityToolkit/blob/35d7d5f7620110a55de9ec8a1afd0397e64b4d10/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/iOS/PopupRenderer.ios.cs#L134~L149

since you don't have a `MainPage` that will be null. That said I believe that our pop-up doesn't support embedded forms scenarios

**Comment by bijington** [comment]
> @follesoe probably the NRE is from here
> 
> https://github.com/xamarin/XamarinCommunityToolkit/blob/35d7d5f7620110a55de9ec8a1afd0397e64b4d10/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Popup/iOS/PopupRenderer.ios.cs#L134~L149
> 
> 
> 
> since you don't have a `MainPage` that will be null. That said I believe that our pop-up doesn't support embedded forms scenarios

I was going to ask whether:
1. We need to set the Parent for the ContentPage
1. And it has to be `Application.Current.MainPage`

I have noticed that we look for `Application.Current.MainPage` throughout the code but I suspect this is to gain access to an `INavigation` implementation. If we only need an implementation could we allow developers to provide their own?

```csharp
public Func<INavigation> NavigationProvider { get; set; }
```

Then a consumer could write something that maps to purely Xamarin.iOS.

I don't know if this provides less effort for them over just showing a popup directly themselves. What are your thoughts? @VladislavAntonyuk might also have some thoughts

**Comment by ahoefling** [comment]
Thanks @follesoe for logging the issue so we can get more eyes on it. To the best of my understanding the Xamarin.Forms navigation pipeline isn't being created in the embedded scenario even though you are creating a `MainPage` object. I wasn't 100% sure when I originally made the recommendation on twitter.

The exception is thrown when the renderer is attempting to gain access to the nearest `ViewController` which is required to attach the native iOS popover to. Since this was built with the assumption of Xamarin.Forms usage we decided to use the `MainPage` which has a `ViewController` we could access and attach the popover to. 

If we want to support Xamarin Native scenarios we may just need to add an extension method that allows the invoking code to pass their current `ViewController`. Then the method `SetViewController` can be skipped and the popover should render on the provided `ViewController`. Since xamarin native doesn't technically have an `INavigation` interface I am not sure the best place to add the extension method. I worry about API abuse if we add the extension method or create a global object. I don't want to create an API that will be easy to abuse from a Xamarin.Forms project as we want those applications using the `INavigation` interface. Wherever we decide to place the contract, I see it looking something like this

```c#
void ShowPopup(Popup popup, ViewController viewController);
```

### Android Considerations
To properly add support for xamarin native we will need to consider how the Android Dialog is rendered. We may need to create a similar API that allows the consuming code to pass the Android `Activity. That API signature may look like this

```c#
void ShowPopup(Popup popup, Activity activity);
```

**Comment by VladislavAntonyuk** [comment]
By setting ViewController I've made it work.
But you shouldn't use Navigation.ShowPopup. Navigation is from Xamarin.Forms and Xamarin set their own Window.RootController (from MainPage renderer).
I propose such usage:
```
var popupRenderer = new PopupRenderer(this);
((IVisualElementRenderer)popupRenderer).SetElement(popup);
```
![image](https://user-images.githubusercontent.com/33021114/145636302-649078dc-983d-4d2f-9276-8bf97c415199.png)
