### ISSUE TITLE
[Enhancement] Integrate as much MvvmHelpers as possible :)

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/XamarinCommunityToolkit#190]
## Summary

Please take it all -> https://github.com/jamesmontemagno/mvvm-helpers

**Comment by sthewissen** [comment]
Such wow! Much thanks!

Awesome @jamesmontemagno

**Comment by jamesmontemagno** [comment]
TAKE IT ALL

**Comment by AndreiMisiukevich** [comment]
@jamesmontemagno 

![image](https://user-images.githubusercontent.com/10124814/89689356-e13e1a80-d90c-11ea-9106-3a425757f1a8.png)

**Comment by roubachof** [comment]
YES TAKE IT ALL (but not the `IsBusy` part please)

**Comment by IeuanWalker** [comment]
@roubachof @AndreiMisiukevich @sthewissen 
Let me know if you want help with this.

Maybe open an issue for each of the features MVVMHelpers has.

**Comment by adenearnshaw** [comment]
There's potentially some crossover in functionality between this and the MvvmToolkit being developed via the [WindowsCommunityToolkit](https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Mvvm).

It's already a net standard package and it seems they are aiming to provide Xamarin compatibility for that package going forward.

It could be worth cherry picking the items that aren't covered in that rather than duplicating, however that may raise the question of dependencies on other packages?

**Comment by jfversluis** [comment]
@IeuanWalker if that is something you're willing to do, feel free to open an issue per feature so we can track it by that.

@adenearnshaw thanks, yes we're aware and one of our future plans is to see if we can collaborate with them to see where we overlap and how we can unite that. I think that will make more sense by the time .NET MAUI lands though.

We're definitely not looking to duplicate things or fragment the ecosystem. If anything, what we're trying to do is convince library authors to contribute their wonderful work to us so we can bundle it better and offload the burden they might feel of maintaining it.

**Comment by michael-hawker** [comment]
Just found out about this issue. 

Agree with @jfversluis, we shouldn't be duplicating efforts and adding helpers to the Xamarin Toolkit if there's other things in the ecosystem. As @adenearnshaw pointed out we should align on the new **.NET Standard** MVVM Toolkit we've been building since April in the Windows Community Toolkit. We could use some help with a Xamarin sample here: https://aka.ms/mvvmtoolkit.

**Comment by Cfun1** [comment]
@jamesmontemagno ,@jfversluis How are we tracking when this done? Maybe a Task list of Items that will be integrated will be helpful.

**Comment by Cfun1** [comment]
@jamesmontemagno ,@jfversluis How are we tracking when this done? Maybe a Task list of Items that will be integrated will be helpful.

**Comment by DominicMaas** [comment]
Any updates on reducing the duplicating efforts between the MVVM helpers in this toolkit and the Microsoft.Toolkit.Mvvm? Would it make sense for the Xamarin Community Toolkit to depend on `Microsoft.Toolkit.Mvvm` to try reduce fragmentation?

**Comment by michael-hawker** [comment]
@DominicMaas we do have a XF sample in the Toolkit samples now: https://github.com/windows-toolkit/MVVM-Samples/tree/master/samples/MvvmSampleXF

It'd be great to reduce any redundancy. Is that something you'd be up for helping with?

@brminnick @jfversluis I know we talked about this briefly, any thoughts for here and in the future?

**Comment by roubachof** [comment]
I think we would like to keep XCT as mvvm-agnostic as possible. There are already great frameworks which the Xamarin.Forms users are familiar with, like Prism and FreshMvvm. XCT is more about controls, converters, behavior, effects, etc...

**Comment by michael-hawker** [comment]
@roubachof yup, agree. Edited my comment above, keep forgetting that 'Toolkit' is ambiguous. We have a .NET Standard MVVM Toolkit implementation (a successor to MVVM Light) that supports Xamarin, UWP, WPF, etc... So, it'd be great to minimize the overhead in the XCT by pointing folks to that or other great .NET Foundation MVVM libraries than maintaining an extra one here.

There are certainly some helpers for handling tasks/async commands in the UI which may need Xamarin specific implementations (we have one UWP helper) that would still make sense to keep within the XCT space.

**Comment by jfversluis** [comment]
I think we took the most valuable parts for now and are holding off with the rest until we can reveal our future plans... 🙀
