### ISSUE TITLE
[Enhancement] Snackbar

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#197]
## Summary

The base changes were made here: https://github.com/xamarin/Xamarin.Forms/pull/9324

Does it the right place to implement it? What is the future of this library after MAUI release?

**Comment by jfversluis** [comment]
Hey @VladislavAntonyuk thank you for wanting to bring this over here. I personally think it will be a great addition.

Unfortunately, my crystal ball broke so I can't tell you exactly what the future is 😉 
I think first and foremost; whenever .NET MAUI is released, not everyone has the capability to switch over from day 1, so Forms will be around for some time to come.

There is also still a lot of time between now and the time that .NET MAUI is released, which will give us the unique opportunity to incorporate controls and other things into the XamarinCommunityToolkit and see how users respond to that first. We can shape the controls make them absolutely stable and once they have proven their value, it should be easy to port those over to .NET MAUI and become first-class citizens. 

.NET MAUI is trying to be as backwards compatible as possible, so it shouldn't be too hard to evolve this library together with that. I'd love to have this library around also for .NET MAUI, but if that will be a possibility is to be seen whenever that time comes.

Does that answer your question? What would you like to se as the future of this?

**Comment by sthewissen** [comment]
I'd definitely welcome a toast/snack type thing as there are not a lof those out there.

Would love if we can make it more templatable / customizable in the visual department!

**Comment by VladislavAntonyuk** [comment]
from my point of view I would investigate into .NET MAUI as a future of Xamarin, so adding a snackbar here is fine, but if it is for 1-2 years it doesn't look reasonable. Also it would be nice to define what is .NET MAUI? is it a core library with minimum code (renders, styles, base controls) and to build a new app I use only plugins which I need (preferable approach from my side)? or is it a power solution with a lot of features in 1 package (converters, custom controls - master page, shell, collection view, etc)

**Comment by jfversluis** [comment]
> from my point of view I would investigate into .NET MAUI as a future of Xamarin, so adding a snackbar here is fine, but if it is for 1-2 years it doesn't look reasonable. 

Like I said, even beyond that 1-2 years, Forms will probably be used for a long time after that by a lot of people. And I think you should see it like this: if the snackbar (or any other) control lives here for only a (short) while, that probably means it was good enough to go into the actual Forms/.NET MAUI package, which is a compliment, right?

The problem there is right now is that Forms will not see any big features until .NET MAUI is released. To account for that, they can live in the XamarinCommunityToolkit at least for a while so people can still benefit from it.

> Also it would be nice to define what is .NET MAUI? is it a core library with minimum code (renders, styles, base controls) and to build a new app I use only plugins which I need (preferable approach from my side)? or is it a power solution with a lot of features in 1 package (converters, custom controls - master page, shell, collection view, etc)

I'm not quite sure what you mean by this. Are you talking .NET MAUI in itself of the Toolkit for .NET MAUI?
There are a good number of articles, blog posts and even videos about .NET MAUI now, there is even [the repository](https://github.com/dotnet/maui) already, where you can see what it is. From the first version it will be everything that Forms has, since it's a copy right now, but things will be improved and expanded from there.

As for the Toolkit, that remains to be seen. I would like to have the Toolkit around also for .NET MAUI since all of what is in the Toolkit should be able to work on .NET MAUI as well. And then from there we can work with the Forms/.NET MAUI team to see what we can transition into .NET MAUI. core and what remains in the Toolkit.

I think this particular feature will be helpful to a lot of people even it was "just" for a couple of years. But of course that is a choice only you can make :)

**Comment by jfversluis** [comment]
@VladislavAntonyuk what is your opinion? You want to bring it over to here, if not, can we do it ourselves?

**Comment by VladislavAntonyuk** [comment]
@jfversluis I am going to start development in September. My original pull request has all necessary code. I will probably need some help with adding customization

**Comment by VladislavAntonyuk** [comment]
I see that toolkit currently doesn’t support all platforms which XF does. Should I implement snackbar for all of them?

**Comment by VladislavAntonyuk** [comment]
In progress

**Comment by VladislavAntonyuk** [comment]
@jfversluis I created a draft PR, could you please check if my solution applicable for you requirements of the solution style. I will add more platforms soon

**Comment by jfversluis** [comment]
Thank you so much @VladislavAntonyuk!

This looks very promising, I'm sure we will have some feedback on the PR, but feel free to continue with this and add all the platforms :)
