### ISSUE TITLE
The ability to add overlays onto the camera

### ISSUE THREAD

**Issue by LBally** [xamarin/XamarinCommunityToolkit#445]
The ability to add overlays for IOS and Android on the CameraView control would be really helpful.

**Comment by jBijsterboschNL** [comment]
Have you tried putting the camera view inside a Grid and after the camera view you put your 'overlay'? So that your overlay is rendered on top of the camera view? Or do you also want this overlay being merged on to the image when taking a photo? With images this could be implemented fairly easy by merging the overlay on top of your native image (this would be a platform specific implementation), but for video's I'm not sure how feasible that would be.

**Comment by jfversluis** [comment]
Do you have a bit more information? What kind of overlays? What should they do? How much flexibility do you want? Do you want overlays to be built-in, specify your own template? Why would you just put the `CameraView` as a background and then place semi-transparent elements over it to act as an overlay?

**Comment by domagojmedo** [comment]
I'm not sure how camera view works at the moment. Can you put it as a view inside your page and then put other elements over it? 

Overlays are nice for custom buttons (record/flash/change camera).

**Comment by sarthak1995-26** [comment]
Camera view is itself a ContentView so you can easily put any view above it using grid,absolute or relative layout.

> I'm not sure how camera view works at the moment. Can you put it as a view inside your page and then put other elements over it?
> 
> Overlays are nice for custom buttons (record/flash/change camera).

Yes @domagojmedo  Camera view is itself a ContentView so you can easily put any view above it using grid,absolute or relative layout.

**Comment by domagojmedo** [comment]
I don't really see a need for this issue to remain open then

**Comment by jfversluis** [comment]
Right you are, let's close this one unless there are more specific reasons to want another overlay of sorts

**Comment by michaldivis** [comment]
@LBally all you need to do is wrap the `CameraView` in a `Grid`. Then you can place whatever controls on top of it.
