### ISSUE TITLE
Move C# Markup Extensions from Forms to Toolkit

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#499]
## Summary

The [C# Markup Extensions](https://github.com/xamarin/Xamarin.Forms/tree/5.0.0/Xamarin.Forms.Core/Markup) in its current form need to move from Forms into the Toolkit. 

We want to add this in a separate package from the main one and therefore also a separate (new) namespace

**Comment by VincentH-Net** [comment]
Still blocked by https://github.com/xamarin/Xamarin.Forms/issues/12136

**Comment by VincentH-Net** [comment]
Here is the source for C# Markup including [CSharpForMarkup Part 2 PR](https://github.com/xamarin/Xamarin.Forms/pull/11428) features, in a single commit:

https://github.com/VincentH-Net/Xamarin.Forms/commit/939150d140418191b7bb59c105edee2fab37813f

- Separated C# Markup API + unit tests from Forms projects
- Fully working with 100% code coverage, all tests green
- Using IVT from Forms while waiting for xamarin/Xamarin.Forms#12136

**Comment by jsuarezruiz** [comment]
@VincentH-Net I would like to know how I can help you to move the CSharpForMarkup to the XCT. XCT was recently added to the .NET Foundation and a Support document has been created https://github.com/xamarin/XamarinCommunityToolkit/blob/main/Support.md
@ahoefling Could you share the PRs you created (related with the Popup Control)?. I would like to update the list of blocking points, which have PR and which are still pending.

**Comment by VincentH-Net** [comment]
Thanks for your offer @jsuarezruiz! 

Could you create a PR in Forms to make the API's listed in xamarin/Xamarin.Forms#12136 public (just the ones needed for C# Markup) - and get it merged in Forms 5?

After that I can update the above C# Markup source to that new Forms version and make a PR against XCT. That means the C# Markup XCT package will depend on Forms 5.

Tbc the Xamarin.Forms.Core API's that C# Markup itself needs access to are:

Internal
- `Binding.SelfPath` constant
- `GestureRecognizer` default ctor
- `NullEffect` class

Private
- `FontElement` class
- `PaddingElement` class

In addition, the C# Markup unit tests need to access these API's:

Xamarin.Forms.Core.UnitTests Internal:

- `RelativeLayoutTests.UnitExpressionSearch` class

Xamarin.Forms.Core: private API's on `BindableObject`:

- `GetContext` method
- `BindableContextAttributes enum
- `BindablePropertyContext` nested class
- `SetValueArgs` nested class

If that would be preferred by the team, we could opt to keep the API's only needed for C# Markup unit tests as they are now, and use reflection to access these API's. Since we won't ship the unit tests, that would not introduce any risks for XCT users.

**Comment by ahoefling** [comment]
@jsuarezruiz
>Could you share the PRs you created (related with the Popup Control)?

I have submitted a PR to XCT yet as it needs to support Xamarin.Forms 5.0. The original PR for Popup Control in Xamarin Forms is Xamarin/Xamarin.Forms#9616. 

As of today the only outstanding PR I have to Xamarin.Forms is opening up a few APIs to allow UWP support Xamarin/Xamarin.Forms#12279. 

**Popup Control Ready Platform**
The table below designates which platforms are ready for development once XCT support Xamarin.Forms 5.0
| Platform | Status |
|----------|----------|
| Android | ✔ Ready |
| iOS        | ✔ Ready |
| UWP     | 🔃 Waiting for PR |

**Comment by pictos** [comment]
I think that we can create a branch here targeting Forms 5.0. FYI, The last time that I did it I face some issues with `PancakeView` and controls can have an odd behavior  (like camera view)
