### ISSUE TITLE
[Proposal] RadioButton

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#5]
_From @jamesmontemagno on December 23, 2016 7:7_

Details coming soon

_Copied from original issue: FormsCommunityToolkit/Controls#2_

**Comment by weitzhandler** [comment]
I'd like to contribute.

**Comment by jgiacomini** [comment]
Any help needed?

**Comment by weitzhandler** [comment]
This project looks so dead.

**Comment by skendrot** [comment]
If you would like to contribute then submit a PR

**Comment by weitzhandler** [comment]
I wish they ever accept your PR...

**Comment by skendrot** [comment]
Huh? There's only three PRs. The oldest is fine months but it is waiting for changes

**Comment by weitzhandler** [comment]
@skendrot I wish you were here last July. I was really into submitting a PR, but getting through all the testing and effort with getting no response held me down. Unfortunately now I'm not on a XF project anymore. But hopefully I'll get back.
At least it's nice to see that this essential project is getting the basic maintenance and responsiveness it deserves. Thank you!

**Comment by pauldipietro** [comment]
We're looking to get an official 1.0 together primarily based off of what currently exists in the project, but for a vNext/1.1, if we start adding in controls, a radio button might be worth looking into assuming a proper spec.

**Comment by jamescurran** [comment]
I've created a (Xamarin.Forms) control which is RadioButton-ish, which suited my need, and may be useful to other, but isn't quite a proper RadioButton.
Best explained with an example.  A person record has a gender field which is stored as "M" or "F".  I wanted a control the would display "Male" and "Female" as buttons, but bind "M" or "F" to the Value:

     <jmc:RadioButton  ItemSource="M=Male;F=Female" Value={binding Gender}"   />

in another place in the app, i use:
  
     <jmc:RadioButton  ItemSource="L=Leading;S=Supporting;F=Featured" Value={binding RoleType}" />

It works nicely in places where you'd otherwise have to use a Switch or a Picker. 

Would there be any interest in that in the library??

**Comment by darshanrampatel** [comment]
@jamescurran Is there a limit of the number of buttons your control can handle? If not, it sounds interesting...

**Comment by jamescurran** [comment]
I put no arbitrary limit on the number of buttons.  Since I'm just stuffing them into a horizontal StackLayout, I imagine that there's is a practical limit somewhere.

**Comment by jfversluis** [comment]
RadioButton is now a control in Xamarin.Forms, this is therefore outdated
