### ISSUE TITLE
Long tap gesture behaviour

### ISSUE THREAD

**Issue by sarthak1995-26** [xamarin/XamarinCommunityToolkit#500]

**Comment by AndreiMisiukevich** [comment]
That's definitely a good idea) Would you like to bring this behavior?

**Comment by felipebaltazar** [comment]
Hi everyone!
Can I work on this issue?

**Comment by pictos** [comment]
Since the author didn't say anything about it, I think that you can do it @felipebaltazar, can you add a little spec in this issue before you start to implement? Thanks in advance.

**Comment by jfversluis** [comment]
Also please think about how we can implement this maybe more generic and also support other gestures that are available instead of focusing in just this one

**Comment by freever** [comment]
Have a look at this thread on the Maui repo: https://github.com/dotnet/maui/discussions/107

The author of the MR Gestures library was willing to contribute it to Maui, but the toolkit might be a better home for it. 

I have used MR Gestures before because I needed pinch gestures on a Skiasharp canvas, and it worked great.

**Comment by roubachof** [comment]
Would be great if we can have mr gestures on the team. All of my apps use it 😄

**Comment by AndreiMisiukevich** [comment]
FYI

I am working on moving TouchEffect here
LongPress would be supported by it

https://github.com/AndreiMisiukevich/TouchEffect

But I am not against your try 👍

**Comment by roubachof** [comment]
@MichaelRumpler would you be interested in merging your gesture library to the XamarinCommunityToolkit :) ?

**Comment by MichaelRumpler** [comment]
> @MichaelRumpler would you be interested in merging your gesture library to the XamarinCommunityToolkit :) ?

IMHO the biggest downside of [MR.Gestures](http://www.mrgestures.com/) is, that you have to use its own elements. I.e. `MR.Gestures.Label` instead of `Xamarin.Forms.Label`. The only way to change that is to add all the events and properties to `Xamarin.Forms.Element` directly. The Community Toolkit cannot do that.

I also need to overwrite some methods in the native renderers to hook everything up and to clean up when the view is not used anymore. So I cannot use attached properties either.

**Comment by felipebaltazar** [comment]
I was thinking to try extends DragNDrop gesture, thats already intercepts LongPress, for this...
So, we can use like any other gesture

https://github.com/xamarin/Xamarin.Forms/pull/11537/files#diff-e6e3888e703afef4efdc3ac2b09c15b344cd4f4f7b9f99d2b60295f189a60b88R212
