### ISSUE TITLE
[Enhancement] Decouple Xamarin.Forms.Page from SnackBar

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/XamarinCommunityToolkit#504]
Hi.

Considering that SnackBar is a generic notification service I think it would be useful if displaying them did not require to send in a page. ACR's equivalent doesn't require a page, and if XCT's equivalent could be made not to require one it would be great. In my case for example I am listening to some network events and display toasts based on them, where the listener has no concept of a page. These notifications can happen anywhere in the app, and considering that the snackbar is drawn on top of any page I am wondering if this requirement could be removed?

Alternatively, if it just needs a page (any page) is there a reason it's not just piggybacking on Application.Current.MainPage internally?

Thank you.

**Comment by oscarjaergren** [comment]
It's so strange that the Snackbar was built in with a page from that start when other controls such as toast did not.

**Comment by Cfun1** [comment]
According to Android documentation [Make() method](https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar#make) requires a View, since xct is using the native on, not sure we can do much with the native implementation, although we can extend from Page to other Views .

**Comment by dersia** [comment]
MHO the Snackbar is broken, because it requires the page to be called and especially for MVVM flows this won't allow the user to Display a Snackbar or Toast.
While thinking about it, I couldn't come up with a reason, why the page is needed for it. A Snackbar or Toast is going to always be displayed on the CurrentPage. I can't think of a reason why one would like to display a Snackbar on any other page than the current.
Sure, when we talk about Multi-Window Application, or even a TwoPaneView, but neither for a Multi-Windows Application nor for a TwoPaneView a Page will be sufficient to decide where to display the Snackbar or Toast.

Therefor I suggest to change the Snackbar to always display on the CurrentPage so it'll be accessible from everywhere and can be part of the Dependency-System or just as a static class. In the Renderer we should have access to the current page and this feature should be quite easy to implement.

@Cfun1 the `CurrentView` should be available when calling Make() and as far as I could see in the source of the android renderer the page is just casted to a view befor make is called.

**Comment by AndreiMisiukevich** [comment]
@dersia just wonder how do you usually display Alerts and ActionSheets?) They require Page as well

**Comment by dersia** [comment]
@AndreiMisiukevich well you could say the same about popups. I really think there were some design flaws when those where speced (I often have the feeling, that those who worked on the original specs at xamarin just weren't MVVM users and didn't think about the implications), but maybe I am missing something and don't know all the reasons why Alerts and ActionSheets where desgined this way.

For android when we look at 
https://github.com/xamarin/XamarinCommunityToolkit/blob/caa3ebc71335d68e4a69758def542b322ccdbf90/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/Snackbar/SnackBar.android.cs#L19
we can see, that it's just getting the view from the page and since we are already on Platform side, we should be able to get the current Page, right? So after we got the current page we should be able to just get the view and nothing else should change, right?

**Comment by AndreiMisiukevich** [comment]
@dersia if we speak about **strict** MVVM, then you cannot call the snack bar directly from your ViewModel (because it belongs to the Presentation Layer). 

As for the CurrentPage.

If I use TabbedPage, for example, the Application.CurrentPage is "TabbedPage", not TabbedPage.Current.

And I can show snack bar above the root (TabbedPage), but also can put it over ContentPage that is inside TabbedPage.

**Comment by matsydoodles** [comment]
It is a tough one, because out of the box someone new to Xamarin with no MVVM experience probably can hit the ground running with this. However someone who is new to Xamarin but not to MVVM it is not as obvious. It took longer than I care to admit to realise it was done off of a `PageExtension`. Once I did it was fairly straightforward what I had to do. Someone who is new to Xamarin and MVVM might struggle with.

I've ended up writing my own `SnackBarService` where I `Subscribe` to it in my `Page` constructor and then `Send` in my `ViewModel`. It is using the `MessagingCenter` under the hood to Send/Subscribe the messages between.

**Comment by VladislavAntonyuk** [comment]
@AndreiMisiukevich since snackbar uses VisualElement instead of the ContentPage, can we close this bug? I don't think we will fully decouple SnackBar from the UI as described in the bug.
Even if we create `DialogService` and hide the UI elements from the method parameter it will use Application.Current.MainPage inside as the default anchor. I think the customer can implement it as they wish.
```
public class DialogService : IDialogService 
{
   public Task DisplayToastAsync(string text)
   {
      return Application.Current.MainPage.DisplayToastAsync(text);
   }
}
```

in this case, your library with the interface doesn't depend on Xamarin.Forms

**Comment by Tommigun1980** [comment]
> @AndreiMisiukevich since snackbar uses VisualElement instead of the ContentPage, can we close this bug? I don't think we will fully decouple SnackBar from the UI as described in the bug.
> Even if we create `DialogService` and hide the UI elements from the method parameter it will use Application.Current.MainPage inside as the default anchor. I think the customer can implement it as they wish.
> 
> ```
> public class DialogService : IDialogService 
> {
>    public Task DisplayToastAsync(string text)
>    {
>       return Application.Current.MainPage.DisplayToastAsync(text);
>    }
> }
> ```
> 
> in this case, your library with the interface doesn't depend on Xamarin.Forms

Is there ever a use case where Application.Current.MainPage wouldn't be used? The notifications seem to pop up over everything else (as they should) when Application.Current.MainPage is used no matter what elements exist on top of it.

So in that regard, is there any reason to actually expose the view as an argument in the API if it will always be Application.Current.MainPage (unless there's a use case I'm missing)? Would it make sense to just do that internally and not expose the view as an argument?

(If you do it, please take into account that Application.Current.MainPage may be null -- for example if the app is launched from a notification and the notification code is executed before a main page has been constructed.)

**Comment by brminnick** [comment]
Thanks! However, we are no longer adding new features to Xamarin Community Toolkit, focusing on the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui).

Please open a [New Feature Discussion](https://github.com/CommunityToolkit/Maui/discussions/new) to implement this feature in the .NET MAUI Community Toolkit.

I've posted more information about the Future Of Xamarin Community Toolkit here: https://devblogs.microsoft.com/xamarin/the-future-of-xamarin-community-toolkit/?WT.mc_id=mobile-0000-bramin
