### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by biapar** [xamarin/XamarinCommunityToolkit#521]
Where is the documentation?

**Comment by Hackavist** [comment]
https://github.com/MicrosoftDocs/xamarin-communitytoolkit

**Comment by jfversluis** [comment]
As @Hackavist pointed out there is the repo, but we're still working on getting it complete. That's why it's not published yet.

Before the stable package lands we will make sure that it's published and ready for you to use.

Of course, you are very welcome to contribute to the Docs to get there faster :)

**Comment by biapar** [comment]
> As @Hackavist pointed out there is the repo, but we're still working on getting it complete. That's why it's not published yet.
> 
> Before the stable package lands we will make sure that it's published and ready for you to use.
> 
> Of course, you are very welcome to contribute to the Docs to get there faster :)

Hi, Where to start?

**Comment by jfversluis** [comment]
I'm not sure what you mean by this? 

What we have right now is on this repo: https://github.com/MicrosoftDocs/xamarin-communitytoolkit in markdown files and a couple of PRs. You can see in the issues there what is still missing
