### ISSUE TITLE
[Enhancement] Update Forms dependency to XF5

### ISSUE THREAD

**Issue by jfversluis** [xamarin/XamarinCommunityToolkit#562]
## Summary

More and more good stuff is added to Xamarin.Forms 5, to make optimal use of all of that goodness, let's update our dependency to Xamarin.Forms 5 as well. This has one bigger implication for the stable release: we need to wait for a Forms 5 stable release before we can do ours, but we're close enough to the fire to make that happen on the same day.

If a lot of requests come in for effects, behaviors and/or converters for lower Forms versions we will handle it then

@pictos, you have looked into this? Were there issues with doing this?

**Comment by pictos** [comment]
When I tried I faced some runtime errors, one of them was caused by `PancakeView` and some controls also failed. I'll try it again and maybe create a XF5.0 dependency-branch here. I reported my experience on XCT discord's channel, you can find the first message [here](https://discord.com/channels/732297728826277939/738065609740517467/762690350363967578).

**Comment by pictos** [comment]
Testing again... 

## Core

* Ambiguity on `WeakEventManager`, we need to decide which one we will use (Forms or ours), maybe change the name?
> This also affects our users, because now that XF opens its implementation of `WeakEventManager` users can be confused about which one they would choose. I can remember that @brminnick said that ours is more robust than XF.


## Android

* We need to dropoff the MonoAndroid9.0 from TargetFrameworks and just compile MonoAndroid10 and above
* Some ambiguity with members names in forms (it's easy to fix)
* Change some references to use `Xamarin.AndroidX` instead of the `Xamarin.Android.SupportLibs`
* PancakeView errors, need to upload to preview version;
> Thanks @sthewissen for the quick fix you are awesome!

## iOS, UWP and WPF

* Just works.

## GTK and Tizen

* I didn't test.

## Actions

Since I could make it build, I created this [branch here](https://github.com/xamarin/XamarinCommunityToolkit/tree/target-forms-5.0) with this update. 
**If you need to open a PR that needs XF5.0 use this branch as a test, but - for now - it's just a POC.**

**Comment by jfversluis** [comment]
For the Android bits; does that mean we can also use the AndroidX CameraView?

Not too concerned about all of that. The WeakEventManager sucks though... Any suggestions?

**Comment by pictos** [comment]
@jfversluis 
> For the Android bits; does that mean we can also use the AndroidX CameraView?

I think that we can use CameraViewX but it's in beta right now. If we are ok with it I can do a spike on that.

> Not too concerned about all of that. The WeakEventManager sucks though... Any suggestions?

I would like to wait for @brminnick input on this one.

**Comment by brminnick** [comment]
Hi Friends! 

Here's my recommendation:
- Remove `Xamarin.CommunityToolkit.Helpers.WeakEventManager`
- Keep `Xamarin.CommunityToolkit.Helpers.WeakEventManager<TEventArgs>`
- Migrate all `Xamarin.CommunityToolkit.Helpers.WeakEventManager` dependencies to `Xamarin.Forms.WeakEventManager`
  - E.g. In `Xamarin.CommunityToolkit.ObjectModel.BaseCommand`, replace `Xamarin.CommunityToolkit.Helpers.WeakEventManager` with `Xamarin.Forms.WeakEventManager`

**Comment by brminnick** [comment]
WeakEventManager PR done: https://github.com/xamarin/XamarinCommunityToolkit/pull/597 🎉 

The plan to use extension methods was thwarted because Xamarin.Forms.EventManager uses a private field for `Dictionary<string, List<Subscription>> _eventHandlers`, which the extension methods could not access.

The workaround was to rename `Xamarin.CommunityToolkit.Helpers.WeakEventManager` to `Xamarin.CommunityToolkit.Helpers.DelegateWeakEventManager`

**Comment by jfversluis** [comment]
OK I think this is all done!

**Comment by JunkyXL86** [comment]
> The plan to use extension methods was thwarted because `Xamarin.Forms.WeakEventManager` uses a private field for `Dictionary<string, List<Subscription>> _eventHandlers`, which the extension methods require but could not access.

So why does the DelegateWeakEventManager the same and keep the subscriptions private? I'm working on a project that needs to do some actions when the last handler has been removed. Thus I need to know the subscription count. For now I have to count the registrations by myself.
