### ISSUE TITLE
[Bug] [iOS] Expander + CollectionView: expanding wrong cells.

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/XamarinCommunityToolkit#568]
### Description
Expanding several other cells during expanding any "cell".
If then you try to scroll collection a little, the bug will go.

I assume there is a bug somewhere in TemplatedCell of iOS-specific code.

**iOS** Only.
### Steps to Reproduce
1) Download sample
2) Run it on iOS simulator
3) Try to expand any cell

**Works fine on Android.**

### Expected Behavior
Expanding only one "cell" like on Android that was pressed.

### Actual Behavior
Expanding several "cells".

### Basic Information

- Version with issue:
- Last known good version: none
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS:  latest
- Affected Devices: iPhone 11 Simulator

### Screenshots
![Apr-08-2020 00-25-41](https://user-images.githubusercontent.com/10124814/78721073-88934c80-792f-11ea-8cc0-31d33cbb0749.gif)

### Reproduction Link
https://github.com/xamarin/Xamarin.Forms/files/4440579/ExpanderTest.zip

**Comment by jfversluis** [comment]
We've added to the [Docs](https://docs.microsoft.com/xamarin/community-toolkit/views/expander): Expander and CollectionView/ListView should not be used together. I'd love to have a solution for this but it’s one of those controls that don’t exist on the native platform. Because of that you will be fighting the OS on getting it right. Closing this one since there won't be any solution on the short-term unless someone contributes it.
