### ISSUE TITLE
[Bug] Expander + Grouped CollectionView issues

### ISSUE THREAD

**Issue by Reveon** [xamarin/XamarinCommunityToolkit#569]
### Description
There are some issues when using Expander in grouped CollectionView on ios.

iOS 13 - it behaves the same as described in xamarin/XamarinCommunityToolkit#568 
iOS 12 - Items 0-2 are expanded correctly but when I try to expand 3 or 4 then the Header item goes back to its original position and overlaps with the expander.
iOS 11 - the app crashes when I select an item

### Steps to Reproduce

1.  Run the repro sample
2.  Run an emulator for different iOS versions and try to expand and item

### Expected Behavior
Expander behavior in grouped CollectionView is consistent in all iOS versions

### Actual Behavior
There are some issues on different iOS versions

### Basic Information

- Version with issue:
- Last known good version:
- IDE: 
- Platform Target Frameworks: 
  - iOS:  tested on iOS simulators 11,12 and 13

### Screenshots

![iOS12_Correct](https://user-images.githubusercontent.com/29383312/79046856-8ec94780-7c13-11ea-9d2c-dd4b2c9fc997.png)
![iOS12_4](https://user-images.githubusercontent.com/29383312/79046872-9c7ecd00-7c13-11ea-9cfa-ee87b03eabc3.png)

### Reproduction Link
[CollViewEpxanderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4464785/CollViewEpxanderTest.zip)

**Comment by jfversluis** [comment]
We've added to the [Docs](https://docs.microsoft.com/xamarin/community-toolkit/views/expander): Expander and CollectionView/ListView should not be used together. I'd love to have a solution for this but it’s one of those controls that don’t exist on the native platform. Because of that you will be fighting the OS on getting it right. Closing this one since there won't be any solution on the short-term unless someone contributes it.
