### ISSUE TITLE
Remove ms-appx:// from the Source

### ISSUE THREAD

**Issue by jrahma** [xamarin/XamarinCommunityToolkit#577]
Hi,

Why do we need to add ms-appx:// when playing a local file?

`<MediaElement Source="ms-appx://XamarinShow_mid.mp4" />
`

It will be great if you just change it to:

`<MediaElement Source="XamarinShow_mid.mp4" />
`

and let Xamarin Forms itself to add the ms-appx://

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by jfversluis** [comment]
Thanks for your suggestion!

I see a couple of issues with this though; this should happen only for UWP. I think adding the `ms-appx://` is a common practice whenever you want to access something within your app. I can also imagine scenarios where you might want to get it from maybe your filesystem with C:\ etc.

To be honest, I don't think the gain outweighs the costs here with all the potential bugs and unwanted behavior. Seeing that this has been open since Feb and it hasn't gained a lot of traction I don't think the ask for this is very big, so closing this for now.

I hope you will propose other great enhancements in the future though, I have seen a lot of ideas from you Jassim! Thank you!
