### ISSUE TITLE
[Proposal] RangeSelector

### ISSUE THREAD

**Issue by bartlannoeye** [xamarin/XamarinCommunityToolkit#6]
_From @jamesmontemagno on December 23, 2016 7:8_

Via: http://docs.uwpcommunitytoolkit.com/en/master/controls/RangeSelector/

_Copied from original issue: FormsCommunityToolkit/Controls#3_

**Comment by jamescurran** [comment]
Updated link : https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/rangeselector

**Comment by jfversluis** [comment]
Assuming this is still something people/we might want to add so keeping it here for reference

**Comment by almirvuk** [comment]
This control could be useful. Not sure if this Toolkit library will contain the controls as well.

**Comment by jfversluis** [comment]
I think we can have controls. The way I see it is that we could/would take controls that we want to battle test first. So it's even a step before the Forms experimental basically. It's a thin line though which should go in here and which should just end up in Forms directly.

That is probably a matter of demand. If people are requesting a certain control and gains popularity, we should probably put it in Forms directly. Else, we can try out here, see how it works and behaves and if all goes well, we could still pass if over to Forms.

**Comment by SunnyMukherjee** [comment]
I've seen a few repos pop up and fade away over time.  Here is one example where people wanted to create extended controls with more features that do not come out of the box in XF.  I may have used this repo too at one point.  The last commit was more than 3 years ago.

https://github.com/XLabs/Xamarin-Forms-Labs

Such repos were created for submitting new controls, seeing if they gain popularity, and then adding them to Xamarin Forms.  I think the ImageButton is the only one from this repo that made it into XF, maybe not the code itself but the concept.  

I have seen the SegmentedControl implemented in a number of repos and 3rd party toolkits that has yet to make it into XF.  It's one of the most popular control requests out there.  I use this feature too in my projects.  I hope it gets absorbed at some point into XF as a standard control.

And I hope this repo does not fade away over time (hopefully because it has the backing of some influential XF people).

**Comment by AndreiMisiukevich** [comment]
Here is what we want: https://github.com/halkar/xamarin-range-slider

**Comment by jfversluis** [comment]
@AndreiMisiukevich we could reach out to this person and see if they are interested in contributing it to this library?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich we could reach out to this person and see if they are interested in contributing it to this library?

Sounds like a good plan.
