### ISSUE TITLE
LabelSizeFontToFit decreasing font 

### ISSUE THREAD

**Issue by aneshad** [xamarin/XamarinCommunityToolkit#60]
Need help - maybe it's my own fault:

When I use LabelSizeFontToFit with static text for label everything is just fine.

When label text is changing (for example in for loop) font size is smaller and smaller in every iteration and converge to one pixel. 

## Bug 

Version Number of Plugin: version="1.0.0.110-beta" 
Device Tested On: Alcatel Pixi
Simulator Tested On: Android emulator API 21

### Expected Behavior
to change (decrease) font size once
### Actual Behavior
decreasing font size in for/next loop in every iteration
### Steps to reproduce the Behavior

Label, XAML definition
```
<Label x:Name="pbText" Text=" " HorizontalOptions="StartAndExpand" VerticalOptions="Center" 
	Font="{StaticResource fontAccNoCases}" LineBreakMode="NoWrap" 
	IsVisible="{Binding Source={x:Reference pgMain}, Path=IsBusy}" >
        <Label.Effects>
               <effects:LabelSizeFontToFit />
         </Label.Effects>
</Label>
```
C#:

```
for (int i = 0; i < nCasesToUpdate; i++)
{
	await some_func();
        pbText.Text = $"Working on " {i + 1} / {nCasesToUpdate}";
}

```

**Comment by bowman-jm** [comment]
I am seeing the same behavior. Any ideas what is causing this?

**Comment by bowman-jm** [comment]
@aneshad I was able to copy the source and find the root of the problem.. Since there is hard coded threshold of 0.5 pixels every time the layout changes (e.g your text changes).. The loop which determines the new size only goes until it is within 0.5 and then set the new size.. which is always going to be smaller by less then 0.5.. but greater then 0.. hence the small increments of being smaller!

As far as the fix for this as it exists, since I only care about the line fitting only if the text doesn't fit because its too big, I simply check if its the first time through the loop, and if it is considered too small (which I want, I break the loop)

```
       public void OnLayoutChange(Android.Views.View v, int left, int top, int right, int bottom, int oldLeft, int oldTop, int oldRight, int oldBottom)
        {
            if (_textView.Width <= 0 || _textView.Height <= 0) return;

            var hi = ConvertSpToPixels(_textView.TextSize, _textView.Context);
            var lo = 1f;

            var paint = new Paint(_textView.Paint);
            var bounds = new Rect();
            **bool isFirst = true;**
            while ((hi - lo) > Threshold)
            {
                float size = (hi + lo) / 2;
                paint.TextSize = size;
                paint.GetTextBounds(TextMeasure, 0, TextMeasure.Length, bounds);

                if (paint.MeasureText(_textView.Text) >= _textView.Width || bounds.Height() >= _textView.Height)
                    hi = size; // too big
                else
                {
                    **// If the text is too small, we are good we only wanna make sure it fits, not fits exactly
                    if (isFirst)
                    {
                        lo = hi;
                        break;
                    }**
                    lo = size; // too small                 
                }
                **isFirst = false;**
            }

            _textView.SetTextSize(ComplexUnitType.Px, lo);
        }
```

**Comment by berlamont** [comment]
@bowman-jm Nice work, this helped me out, might be worth doing a pull request for?

**Comment by bowman-jm** [comment]
Hi @berlamont ,

This did seem to help me for a while too, but then I started seeing the same issue again in some cases in my App, even though it appears to be less common. I haven't had the time to dig in and figure it out yet though.

If I can find some time, and do manage to determine the solution, I will create a PR.

Regards,

-Jeff

**Comment by gabrielbunselmeyer** [comment]
Any news on this issue?

**Comment by gabrielbunselmeyer** [comment]
It seems Android now has this feature for TextViews, so enabling it on the OnAttached method might be enough. Couldn't get it to work quite yet though.

**Comment by gabrielbunselmeyer** [comment]
So it's not exactly a fix, but a workaround that for now is doing the job for me:
` if (textView.Width <= 0 || textView.Height <= 0)
                return;

            textView.TextSize = 28f;

            var hi = ConvertSpToPixels(textView.TextSize, textView.Context);
            var lo = 2f;

            var paint = new Paint(textView.Paint);
            var bounds = new Rect();

            if (paint.MeasureText(textView.Text) <= textView.Width)
                return;

            while ((hi - lo) > threshold)
            {
                var size = (hi + lo) / 2;
                paint.TextSize = size;
                paint.GetTextBounds(textMeasure, 0, textMeasure.Length, bounds);

                if (paint.MeasureText(textView.Text) >= textView.Width || bounds.Height() >= textView.Height)
                    hi = size; // too big
                else
                    lo = size; // too small
            }

           textView.SetTextSize(ComplexUnitType.Px, lo);`

Relevant lines are the one resetting the TextSize property to a default 28f and the one returning if the measured text already fits.

The problem seems to be a mix of two things: first, the TextView's actual size is changed when you SetTextSize, for whatever reason. So the next time it runs, it'll check against a much smaller textView.Width than the original, creating a cascading effect until the fontSize is set to a nice 0.

Second is similar: when the code is run the second time around it uses the smaller font from the time before, as in it doesn't reset to the Label's chosen fontsize. Makes sense, but in the case of changing something through a ViewModel Binding it just doesn't work. 

So, as a workaround I put the Label inside a Grid with a set row height and added those lines. I've already spent way too long on this to try thinking of an actual fix, so for now it'll do.

**Comment by jfversluis** [comment]
I think there is a PR for this to be pulled into Forms by default, so this bug will hopefully become irrelevant soon

https://github.com/xamarin/Xamarin.Forms/pull/7981
