### ISSUE TITLE
[Bug] TabView - Tab is not being selected

### ISSUE THREAD

**Issue by MauricioCodeguez** [xamarin/XamarinCommunityToolkit#630]
### Description

The penultimate tab isn't being selected after selecting the last one

### Steps to Reproduce

1.  Download the sample code provided in the re-production link.
2.  Run the sample on an Android device or simulator.
3.  Tap on the last tab.
4.  Try selecting the last but one tab.

### Expected Behavior

Tab is selected

### Actual Behavior

Tab isn't being selected

### Basic Information

- Version with issue: XF 4.8.0.1687
- Last known good version: N/A
- Platform Target Frameworks: 
  - Android: 9, 10

### Reproduction imagery

<kbd><img width="250" src="https://raw.githubusercontent.com/MauricioCodeguez/TabViewDemo/master/art/ezgif.com-gif-maker.gif" /></kbd>

### Reproduction Link

https://github.com/MauricioCodeguez/TabViewDemo

**Comment by Cfun1** [comment]
You have specified versin with issue for Xamarin.Forms only, could you specify XamarinCommunityToolkit version as well ?

**Comment by MauricioCodeguez** [comment]
@Cfun1
The XamarinCommunityToolkit version is **1.0.0-pre5**

**Comment by jfversluis** [comment]
@MauricioCodeguez would you be so kind to try pre6 that has been released this week and verify this is still an issue?

cc: @jsuarezruiz

**Comment by MauricioCodeguez** [comment]
@jfversluis I have tested on the the latest version of the XamarinCommunityToolkit (pre6) and XF (5.0.0.1791-pre5). Unfortunately I am still having the same issue as before

**Comment by jsuarezruiz** [comment]
@MauricioCodeguez Thanks for the feedback. Will review the issue.

**Comment by petrofahed** [comment]
I am having the same issue here.
It could be easily reproduced on the xct.Sample / CustomTabsPage.xaml

- Add new  <xct:TabViewItem Text="Tab5" ....> 
- If you select the last Tab then tab index-1 cannot be selected directly, you need to select other tabs to reenable it 
- Add more tabs on the right side, all index-1 tap as an issue

So the issue is after adding tabs the FAB  on the right side.

**Comment by MauricioCodeguez** [comment]
@jsuarezruiz Is there any news about this issue or a workaround that could be used to avoid the problem?

**Comment by gresolio** [comment]
The issue can be easily reproduced if the TabItems[0] has no content:

```
var customItemNoContent = new TabViewItem { Text = "Custom", Content = null };
var regularItem1 = new TabViewItem { Text = "Tab1", Content = new Label { Text = "Content1" } };
var regularItem2 = new TabViewItem { Text = "Tab2", Content = new Label { Text = "Content2" } };
var regularItem3 = new TabViewItem { Text = "Tab3", Content = new Label { Text = "Content3" } };
var regularItem4 = new TabViewItem { Text = "Tab4", Content = new Label { Text = "Content4" } };

var tabView = new TabView
{
    TabItems =
    {
        customItemNoContent,
        regularItem1,
        regularItem2,
        regularItem3,
        regularItem4,
    }
};

TabViewItem.TabTappedEventHandler onTabTapped = (_, e)
    => Debug.WriteLine($"TabTapped {e.Position}");

TabView.TabSelectionChangedEventHandler onSelectionChanged = (_, e)
    => Debug.WriteLine($"SelectionChanged {e.OldPosition} {e.NewPosition}");

tabView.SelectionChanged += onSelectionChanged;
customItemNoContent.TabTapped += onTabTapped;
regularItem1.TabTapped += onTabTapped;
regularItem2.TabTapped += onTabTapped;
regularItem3.TabTapped += onTabTapped;
regularItem4.TabTapped += onTabTapped;
```

Log with customItemNoContent at index 0:
```
TabTapped 1
SelectionChanged 0 1
TabTapped 2
SelectionChanged 1 2
SelectionChanged 2 1 // SelectionChanged twice
TabTapped 3
SelectionChanged 1 3
SelectionChanged 3 2
TabTapped 2 // Cannot return to index tab-1
TabTapped 2
TabTapped 2
```

Log without customItemNoContent, all items have content, everything works as expected:
```
TabTapped 0
TabTapped 1
SelectionChanged 0 1
TabTapped 2
SelectionChanged 1 2
TabTapped 1
SelectionChanged 2 1
TabTapped 0
SelectionChanged 1 0
```

My use case: two custom elements on the sides without content (status + button) and the regular tab items in the middle:
x Tab1 Tab2 Tab3 x

At the moment I cannot implement this layout due to the tab switching issue.

Xamarin.Forms v5.0.0.1829-pre6
Xamarin.CommunityToolkit v1.0.0-pre6

**Comment by PrajeetShrestha** [comment]
Just tried the TabView from, Xamarin.CommunityToolkit (1.0.0) Stable. This issue still exists. When we select the last TabViewItem, we can't select the second last TabViewItem. Even in the demo given by @davidortinau 
here: https://github.com/davidortinau/LosGatos this issue exists. Hoping for the fix soon :) @jsuarezruiz.

**Comment by SeRgI1982** [comment]
Hi,
I have noticed that this bug is related with TabViewItem without content (FAB from Sample). 
When you enable indicator, you will notice that after tapping on FAB item and items on the right side of FAB item, indicator shows in different position. 
Sometimes you need to tap the same item twice to sync indicator with currently selected TabViewItem and when it happens, you are able to navigate to another (correct) TabViewItem.

According to sample above (.gif), when you tap twice on Profile, than you will be able to tap and navigate to this item with "dolar $" icon.

Checked on Xamarin.CommunityToolkit (1.0.0) Stable version.

**Comment by PrajeetShrestha** [comment]
Is it fixed already?

**Comment by gresolio** [comment]
I'm using the following workaround:

```csharp
/// <summary>
/// Temporary workaround for #595 [Bug] Setting TabView.SelectedIndex does not "visually" switch tabs:
/// https://github.com/xamarin/XamarinCommunityToolkit/issues/595 
/// The BugFix should be merged soon:
/// https://github.com/xamarin/XamarinCommunityToolkit/pull/738
/// </summary>
public class TabViewIndexWorkaround : TabView
{
    public static readonly BindableProperty SelectedIndexWorkaroundProperty = BindableProperty.Create(
        propertyName: nameof(SelectedIndexWorkaround),
        returnType: typeof(int),
        declaringType: typeof(TabViewIndexWorkaround),
        defaultValue: -1,
        defaultBindingMode: BindingMode.TwoWay,
        propertyChanged: OnWorkaroundPropertyChanged);

    private static void OnWorkaroundPropertyChanged(BindableObject bindable, object oldValue, object newValue)
    {
        ((TabViewIndexWorkaround)bindable).UpdateIndexWorkaround((int)newValue);
    }

    public int SelectedIndexWorkaround
    {
        get => (int)GetValue(SelectedIndexWorkaroundProperty);
        set => SetValue(SelectedIndexWorkaroundProperty, value);
    }

    private MethodInfo updateSelectedIndexMethod;

    public TabViewIndexWorkaround() : base()
    {
        updateSelectedIndexMethod = typeof(TabView).GetMethod("UpdateSelectedIndex", BindingFlags.NonPublic | BindingFlags.Instance);
        SelectionChanged += TabView_SelectionChanged;
    }

    private void UpdateIndexWorkaround(int index)
    {
        try
        {
            updateSelectedIndexMethod.Invoke(this, new object[] { index, false });
        }
        catch (Exception ex)
        {
            Debug.WriteLine("UpdateSelectedIndex Ex: " + ex);
        }
    }

    private void TabView_SelectionChanged(object sender, TabSelectionChangedEventArgs e)
    {
        SelectedIndexWorkaround = SelectedIndex;
    }
}
```
