### ISSUE TITLE
[Bug] [CameraView] Camera media capture (photo) orientation incorrect on Android

### ISSUE THREAD

**Issue by UKDeveloper99** [xamarin/XamarinCommunityToolkit#751]
### Description

From what I can tell this looks to be a known issue, I've seen the same code used in other Camera2 implementations. The capture output orientation is incorrect from what I can tell on some devices. You can reproduce this with your camera view Android sample. The media capture is rotated 90 degrees to the right.

I found this stack overflow post that could be helpful. The guy posting it uses the same code as yourselves for GetJpegOrientation in your camera fragment class.

https://stackoverflow.com/questions/38282076/how-to-save-images-with-correct-orientation-using-camera2 

### Steps to Reproduce

1. Capture photo in Android

### Expected Behavior

Captured media orientation should match sensor orientation

### Basic Information

- Version with issue: 1.0.0
- IDE:
- Platform Target Frameworks: 
  - Android: 11
- Affected Devices: Oppo Find X2 Pro

**Comment by Gelo-V** [comment]
This happened in my app too in version 1.0.1 , running on Android 10 device.

**Comment by AndreiMisiukevich** [comment]
Hey folks, thank you very much for the report.
Please, feel free to submit a PRs resolving this issue, if you know what exactly should be changed.

**Comment by Gelo-V** [comment]
Hi @AndreiMisiukevich, cool I'll give it a look during this Sunday by downloading the repo and if I'm able to solve it I'll submit the PR. I have never made any contributions before (but I'm wanting to) so I'll explore it first.

**Comment by pictos** [comment]
@Gelo-V if you need any help, please let us know.

**Comment by Gelo-V** [comment]
Hey @pictos thanks for offering your help (I'll need it jajaja)

I got familiar with the solution and tried to dig into this issue, here it is what I found and concluded:

- In the function `TakePhoto()` of the Camera Fragment script the line `sessionBuilder.Set(CaptureRequest.JpegOrientation, GetJpegOrientation());` had no effect on the orientation of the image in my device. If I understood correctly this is what should rotate the preview image.

-  According to the Android [docs](https://developer.android.com/reference/android/hardware/camera2/CaptureRequest.html#JPEG_ORIENTATION): 

>"For EXTERNAL cameras the sensor orientation will always be set to 0 and the facing will also be set to EXTERNAL. The above code is not relevant in such case.              
>This tag is also used to describe the orientation of the HEIC image capture, in which case the rotation is reflected by EXIF orientation flag, and not by rotating the image data itself."

- **Therefore, I believe that the solution is to change the orientation using the EXIF interface.**

However, I found this [article ](https://medium.com/@kenodoggy/solving-image-rotation-on-android-using-camera2-api-7b3ed3518ab6) where it says: 

>"Don’t rely on setting a fixed JPEG_ORIENTATION in the CaptureRequest to work on all devices. Don’t rely on ExifInterface.TAG_ORIENTATION to exist and to provide reliable data on all devices." 

but the solution provided there is already implemented in the CameraView.

So I'm thinking there should be a method that should try to decide which way to set the rotation of the jpeg either by the EXIF tag or in the capture request. Does this make sense? (Sorry, I rarely visit Xamarin.Android or Xamarin.iOS I usually live in Xamarin.Forms jajaja I'm not too familiar with the native API's)

I haven't tried to use the EXIF interface yet since I was getting familiar with the code but we want to use the CameraView in the app we are developing because we can animate it and we want to experiment using paths to clip the view so I'm willing to work on this during this week  if I understood correctly the root of the rotation issue and the solution is viable for the XCT, what do you think?

**Comment by pictos** [comment]
@Gelo-V yeah I know about that article, I used for my studies on `CameraView`. Yeah, you can try to implement that snippet on docs and see how it goes. Hopping that fixed the issue. Please let me know when you can try it.

> Don’t rely on setting a fixed JPEG_ORIENTATION in the CaptureRequest to work on all devices

This is the bad part of the Camera2 API, is very fragmented and you don't have good error handling for that. So we always need to add more cases and checks on the fly.

**Comment by Zubairhanif06** [comment]
here is my demo test project . from the above discussion i did not under stand how to fix it .
[CameraViewDemo.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5835874/CameraViewDemo.zip)
Thanks

**Comment by jfversluis** [comment]
This one is fixed by #886
