### ISSUE TITLE
[Enhancement] Merge Grouping class from MvvmHelpers

### ISSUE THREAD

**Issue by tranb3r** [xamarin/XamarinCommunityToolkit#786]
## Summary

ObservableRangeCollection from MvvmHelpers has already been merged into Xamarin.CommunityToolkit.
I would be interested in merging the Grouping class as well. 

It's basically an ObservableRangeCollection with a Key to identify the group.
It's very useful when using a grouped CollectionView.

What do you think ?

## API Changes

Simply take the class and add it to the ObjectModel namespace.
No breaking change.

## Who Will Do The Work?

I can do the PR if the proposal is accepted.

**Comment by jfversluis** [comment]
We're looking carefully with these things to not have too much overlap with other libraries, especially the Windows Toolkit. But I don't think their MVVM bits already have this do they?

**Comment by tranb3r** [comment]
But ObservableRangeCollection isn't in the Windows Toolkit, right ?

**Comment by tranb3r** [comment]
@jfversluis What's your opinion ? Should we merge more code from MvvmHelpers ? Or just close this issue as "won't be done" ?
This relates to https://github.com/xamarin/XamarinCommunityToolkit/issues/190 which is still open.

**Comment by jfversluis** [comment]
Sorry for the lack of reply! 

Since this is not in the MVVM things of the Windows Toolkit yet and the code is already there I would say we can take this on. Or, if you feel this belong better in the Windows Toolkit and you don't mind the dependency, please feel free to add it there. What is your thoughts about this?

> I imagine this has already been debated, but should xamarin users include both XCT and WCT in their apps ? What is your recommandation ?

As you might've gotten from above, I don't really have any recommendation here. What would you prefer? I can imagine that developers prefer to have one package that has all of what they want. However, as the maintainer we would want to be cautious with not duplicate the same mechanisms over and over again and have different versions with different nuances.

**Comment by tranb3r** [comment]
Honestly, I didn't know about WCT before you mentionned it. 
For sure, I'd rather not depend on one more package. The only reason I would do that would be if all the mvvm stuff was extracted from xct AND from xamarin.forms. I think it would make sense in terms of responsabilities, but I don't think the timing is good for this plan to be realistic.
Also, I'd like to remove my dependency on Refractored.MvvmHelpers, and my understanding (from #190) is that James would like to move as much code as possible from MvvmHelpers into XCT.
The Grouping class is small and I think it's a good helper when using a grouped CollectionView, so short term I think it really makes sense to add it to XCT.
Of course, this is only my opinion, and I'm totally biased...

**Comment by tranb3r** [comment]
@jfversluis Hi Gerald,
Any thoughts ?

**Comment by jfversluis** [comment]
Let's add this one!
