### ISSUE TITLE
[Enhancement] Please keep a compiled APK version of the Samples available to Download

### ISSUE THREAD

**Issue by wagenheimer** [xamarin/XamarinCommunityToolkit#809]
## Summary

I would live to test the samples from Xamarin Community! But I downloaded it from GitHub and was not able to compile it. It would be interesting to always have an updated version of apk form the samples available for download or published on the Google Play Store.

## API Changes

No API Changes

## Intended Use Case
Teste the samples to be able to know the full power of Xamarin Toolkit.

## Who Will Do The Work?
[x] Just putting this out there for someone to pick up

**Comment by domagojmedo** [comment]
I managed to create Android APK with App center 

https://install.appcenter.ms/users/medo.moberg/apps/xct/distribution_groups/public

I'm not sure if sharing links is ok since anything could be in the APK, I'm sorry if it breaks any rules

**Comment by jfversluis** [comment]
I'm thinking I might publish one at some point, not sure, but especially for iOS I don't think we'll get through the store.

Let's not fragment and have a discussion here if needed: https://github.com/xamarin/XamarinCommunityToolkit/discussions/241

I think the trouble was, and also why this issue was opened because it was hard to compile the sample app on Windows, this should be easier with this guide: https://blog.verslu.is/xamarin/xamarin-communitytoolkit/build-xamarin-communitytoolkit-sample-app-windows/
