### ISSUE TITLE
[Enhancement] Markup HotReload

### ISSUE THREAD

**Issue by edsulaiman** [xamarin/XamarinCommunityToolkit#816]
## Summary
is there a hot reload feature in the xamarin community toolkit markup? if there is, how to use it.

also please improve documentation about xct markup, I spent hours searching on google to get started using this library.

**Comment by Cfun1** [comment]
Maybe you need to wait for the coming c# hot reload

**Comment by jfversluis** [comment]
All the documentation that we have right now is here: https://aka.ms/xct-docs

With a specific section on the C# Markup things: https://docs.microsoft.com/en-gb/xamarin/community-toolkit/markup

And the sample in our sample app: https://github.com/xamarin/XamarinCommunityToolkit/tree/main/samples/XCT.Sample/Pages/Markup

As for the reload, I think that's something that is being investigated/developed by the tooling teams, but unfortunately not something we control.

Since there is not much actionable we can do for this issue I'm closing this one for now
