### ISSUE TITLE
[Bug] AvatarView with CollectionView with Shell tabs 

### ISSUE THREAD

**Issue by angelru** [xamarin/XamarinCommunityToolkit#878]
When I use shell tabs with CollectionView and AvatarView when returning to tab the images are "reloaded", this does not happen if AavatarView has no CollectionView, sample attached.

I have tested on android on xiaomi

https://user-images.githubusercontent.com/11645585/107512565-4cf88d00-6ba7-11eb-8e46-8464c5a42ecf.mp4

[AppAvatarView.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/5958208/AppAvatarView.zip)

**Comment by AndreiMisiukevich** [comment]
@angelru can you reproduce this issue if you replace AvatarView by Image?

**Comment by angelru** [comment]
with Image also happens! with ffimageloading it does not happen

**Comment by Cfun1** [comment]
@AndreiMisiukevich could be the same thing happening in sample about page? when scrolling away from already loaded avatars and then coming back the images reload again.

**Comment by AndreiMisiukevich** [comment]
@Cfun1 as was mentioned by @angelru the same problem occurs with raw Image.
AvatarView is based on Image, so the root cause is inside Xamarin.Forms, I believe.
I don't know how can we work around it :(

Only one way, we can add the "ImageFactory" property. So it will be possible to replace Image by CachedImage from FFImageLoading plugin

**Comment by AndreiMisiukevich** [comment]
Closing this issue since it should be done on XF side.
If you'd like to have "ImageFactory" for being possible to switch Image to CachedImage, then please open a new "feature-request" ticket.

Thank you!
