### ISSUE TITLE
[Bug] Popup on UWP throws an exception when accessed from the nightly nuget

### ISSUE THREAD

**Issue by bmacombe** [xamarin/XamarinCommunityToolkit#889]
### Description
![image](https://user-images.githubusercontent.com/15127788/107686230-8fcf6900-6c6a-11eb-9502-87f9708e9c4b.png)

Acts as if the UWP dll isn't being referenced or it's not package correctly.  Works fine in the sample app at the develop branch head at time of report.

Android and iOS work as expected.

### Steps to Reproduce

1. Run the sample app and click the button.

### Expected Behavior
Popup opens

### Actual Behavior
Not supported exception

### Basic Information

- Version with issue: Nightly v.1.1.0-preview1010
- Last known good version:
- IDE: VS 19
- Platform Target Frameworks: 
  - UWP: 1903
- Nuget Packages: Nightly v.1.1.0-preview1010
- Affected Devices:

### Reproduction Link

https://github.com/bmacombe/XCT-Popup-Issue

**Comment by bmacombe** [comment]
@ahoefling @pictos FYI

**Comment by pictos** [comment]
I can confirm it, using the NuGet I can't open the popUp on UWP, but if I reference the XCT source code everything works fine.

**Comment by pictos** [comment]
@jfversluis any thought?

**Comment by jfversluis** [comment]
Well that's interesting. That looks like a rather custom message that is thrown in that exception, but I can't seem to find it.

**Comment by bmacombe** [comment]
Hey @jfversluis, sorry been a bit busy.  But here is where the custom error comes from.

https://github.com/xamarin/XamarinCommunityToolkit/blob/3f7bc8c05f75c979342f1c3cc204e6da9ec363d7/src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/Navigation/NavigationExtensions.netstandard.macos.tvos.watchos.tizen.wpf.gtk.cs#L1-L16

My un-educated guess is somehow that file is being built for UWP instead of the *.uwp.cs.

**Comment by ahoefling** [comment]
As others posted, I am confirming this is happening with the sample project. I added the XCT as a submodule and the latest code in the `develop` branch appears to work.

My initial investigation points to a NuGet packaging issue. I copied the dll from my packages directory for `uap10.0.19041` and then added it as a direct dll reference to the UWP app. When I ran the application the popup displayed without issue. I think the exception is being thrown because the .NET Standard dll is being used from the shared project and it is not swapping out the UWP dll in the project head.

**Comment by inforithmics** [comment]
I had the same problem. The reason was that it didnt work is that my project UWP Project targeted 17763 / 1809
But Xamarin Toolkit was retargeted with the Popup Changes to 19031 / 2004
Which means wen the MinVersion is not 19031 / 2004 it won't work. And it takes the .NET Standard implmentation which is not implemented.

I tried to do a pull request (but I made it of the wrong branch maybe i'll try again). My changes where the following.

changed following line in the Xamarin.CommunityToolkit.csproj

```
 <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);uap10.0.19041;netcoreapp3.1;net472;net471</TargetFrameworks>
```

to

```
 <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);uap10.0.17763;netcoreapp3.1;net472;net471</TargetFrameworks>
    <TargetPlatformVersion Condition="'$(TargetFramework)' == 'uap10.0.17763'">10.0.19041.0</TargetPlatformVersion>   
``` 

which means following 

1. Min Version of UWP that it works is again 17763 / 1809
2. It Compiles it with the SDK Version of 19041 / 2004 
Which means all new Properties /Features are available.

I changed the Code in PopupRenderer.uwp.cs from

```
#if UWP_18362
       if (Element.Color == Color.Transparent)				{
	     flyoutStyle.Setters.Add(new Windows.UI.Xaml.Setter(FlyoutPresenter.IsDefaultShadowEnabledProperty, false));					
#endif
```
to

```
if (ApiInformation.IsPropertyPresent(typeof(FlyoutPresenter).FullName, nameof(FlyoutPresenter.IsDefaultShadowEnabledProperty)))
{
	if (Element.Color == Color.Transparent)
		flyoutStyle.Setters.Add(new Windows.UI.Xaml.Setter(FlyoutPresenter.IsDefaultShadowEnabledProperty, false));
}
```

it checks during the runtime if the isDefaultShadowEnabledProperty is availble end only then it sets it. (Because in 17763 where it runs this Property is not available).

**Comment by inforithmics** [comment]
Another possibility would be to MultiTarget the UWP Version;

changed following line in the Xamarin.CommunityToolkit.csproj

```
 <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);uap10.0.19041;netcoreapp3.1;net472;net471</TargetFrameworks>
```

to

```
 <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);uap10.0.19041;uap10.0.17763;netcoreapp3.1;net472;net471</TargetFrameworks>
``` 
Meaning compiling it for 
 19031 / 2004 and 17763 / 1809

**Comment by ahoefling** [comment]
After further research, I believe this is working as expected and the problem isn't with XCT but the downstream usage in the sample code. 

I have updated the `TargetPlatformMinVersion` to `10.0.19041.0` and everything started working with the latest NuGet. See the new XML below:
```xml
<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
```

@bmacombe can you try applying that change and see if it fixes the problem? If not you can look at the attached sample code which is a fork of your original submission.

[XCT-Popup-Issue_fixed.zip](https://github.com/xamarin/XamarinCommunityToolkit/files/6032087/XCT-Popup-Issue_fixed.zip)

**Comment by bmacombe** [comment]
Appears I can't test it right now as my dev machine still has Win 10 1909, not 2004.  Does it really require 2004 as the min target?  I try to keep my UWP min target to the first version released in the previous year.  Not sure why my machine hasn't bumped up yet, I'll update it and try again.

**Comment by ahoefling** [comment]
@bmacombe 
> Does it really require 2004 as the min target?

This was a discussion and point of concern during the original pull request. The unfortunate answer is yes it is a hard dependency to upgrade to support 19041. You can see some of the discussion in the original thread
* https://github.com/xamarin/XamarinCommunityToolkit/pull/653#discussion_r537581216

This is because the shadow property is not exposed until version 19041. If you try and create a flyout (popups native control) with a transparent background there will be a shadow effect. 

Ideally, in the future we could take a dependency on WinUI 3 which will have Flyout decoupled from the windows version. Until that time we need to bump support for the minimum version.

An alternative is using conditional compile or runtime checks for the feature. I am not sure the best approach as it will be confusing to use and I think the easy solution for developers using the toolkit will just make 19041 a dependency.

**Comment by bmacombe** [comment]
@ahoefling 

I just got my machine on 20H2 and I can confirm it works as expected now.

I normally keep my machines up to date (not sure why my main machine didn't at least have 2004 yet).  But I can say it's lucky if my users always have a windows release that is less than a year old.  I know most should be forced to update it, but my machine wasn't.

Probably going to keep me from adopting XCT in my production app for a while yet.  Did that pre-compiler directive not work to only use the prop when OS >= 2004?  I know it's a relatively short-term problem.

**Comment by bmacombe** [comment]
Is it possible to change that in the ControlTemplate also?  EZ on the forms team showed me that trick.  The ability to change that stuff often exists there even if they haven't added a property to the control.  No idea if that will work in this case, just tossing out the option.

https://github.com/xamarin/Xamarin.Forms/pull/8107#issuecomment-545138683

**Comment by bmacombe** [comment]
@ahoefling I was looking at this again and reading the comments in the PR.  I'm confused why the min needs to be 19041 and not 18362 which is when the shadow property was added?  If the min version was pushed back to 1903 vs 2004 I think that would help with a lot.
